version: '3.8'

services:
  course-service:
    build:
      context: ./CourseService
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8082

  university-service:
    build:
      context: ./UniversityService
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8081

  gateway:
    build:
      context: ./Gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8080
      - COURSE_SERVICE_URL=http://course-service:8082
      - UNIVERSITY_SERVICE_URL=http://university-service:8083

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80" # Assuming the Angular app runs on port 80 inside the container
    networks:
      - app-network
    environment:
      - API_GATEWAY_URL=http://gateway:8080

networks:
  app-network:
    driver: bridge
